trigger: none

variables:
- template: ./iac-variables-template.yml
- group: vg-sample

jobs:
- job: AzureResourceGroupDeployment
  pool:
    vmImage: windows-latest
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: $(AZURE_RM_SVC_CONNECTION)
      action: Create Or Update Resource Group
      resourceGroupName: rg-$(BASE_NAME)-$(ENVIRONMENT_SYMBOL)
      location: $(LOCATION)
      templateLocation: Linked artifact
      csmFile: $(Build.SourcesDirectory)/arm-templates/azuredeploy.json
      overrideParameters: "-base_name $(BASE_NAME)
                          -environment_symbol $(ENVIRONMENT_SYMBOL)
                          -appsrvplan_sku $(APPSRVPLAN_SKU)"
      deploymentMode: Incremental
    displayName: Deploy Azure resources to the environment
